# Example configuration for HTTP Check receiver with TLS certificate checking

receivers:
  httpcheck:
    collection_interval: 60s
    targets:
      # Basic HTTP check (no TLS)
      - endpoint: "http://example.com/health"
        method: "GET"
      
      # HTTPS check with TLS certificate monitoring (default)
      - endpoint: "https://example.com"
        method: "GET"
      
      # HTTPS check with TLS certificate monitoring disabled
      - endpoint: "https://internal-service.local"
        method: "GET"
        collect_tls: false
      
      # Multiple HTTPS endpoints with TLS monitoring
      - endpoints: 
          - "https://api.example.com"
          - "https://www.example.com"
        method: "GET"
        headers:
          User-Agent: "OpenTelemetry-Collector"

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [httpcheck]
      processors: [batch]
      exporters: [logging]