# Example configuration for HTTP Check receiver with timing breakdown and TLS certificate checking

receivers:
  httpcheck:
    collection_interval: 60s
    # Optional metrics (disabled by default)
    # Uncomment to enable timing breakdown and TLS certificate monitoring:
    # metrics:
    #   httpcheck.dns_lookup.duration:
    #     enabled: true
    #   httpcheck.tcp_connection.duration:
    #     enabled: true
    #   httpcheck.tls_handshake.duration:
    #     enabled: true
    #   httpcheck.request.duration:
    #     enabled: true
    #   httpcheck.response.duration:
    #     enabled: true
    #   httpcheck.tls.cert_remaining:
    #     enabled: true
    targets:
      # Basic HTTP check (no TLS)
      - endpoint: "http://example.com/health"
        method: "GET"
      
      # HTTPS check (TLS certificate metrics collected only if enabled above)
      - endpoint: "https://example.com"
        method: "GET"
      
      # Another HTTPS endpoint
      - endpoint: "https://internal-service.local"
        method: "GET"
      
      # Multiple HTTPS endpoints
      - endpoints: 
          - "https://api.example.com"
          - "https://www.example.com"
        method: "GET"
        headers:
          User-Agent: "OpenTelemetry-Collector"

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [httpcheck]
      processors: [batch]
      exporters: [logging]